version: 2.1
executors:
  android-executor:
    docker:
      - image: circleci/android:api-31

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      # Download and install dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - ~/.gradle

      # Build and test the project
      - run:
          name: Build and Test
          command: ./gradlew clean test

          orbs:
  android: circleci/android@2.3.0

workflows:
    example-workflow:
      jobs:
        - android/build:
            executor: abhinav 
